persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_timestamp true
connection_messages true

global_plugin /usr/lib/mosquitto_password_file.so
plugin_opt_password_file /mosquitto/config/passwords

global_plugin /usr/lib/mosquitto_acl_file.so
plugin_opt_acl_file /mosquitto/config/acl

listener 1883
protocol mqtt
listener_allow_anonymous false

listener 9001
protocol websockets
listener_allow_anonymous false
